name: Fetch HKEX OHLC once

on:
  schedule:
    # 08:20 UTC = 16:20 Beijing
    - cron: '20 8 * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requests
        run: pip install requests

      - name: Fetch official OHLC
        run: |
          python fetch_hkex.py --code 02618
          cat latest_price.json
